# Welcome Plugin Configuration
# Version: 1.1.0

# Debug mode for more verbose logging
debug-mode: false

# Message prefix
prefix: "&8[&bWelcome&8] "

# Whether to check whitelist status
check-whitelist: true

# Whether to broadcast a message when a whitelisted player joins
broadcast-on-whitelist: true

# The language to use for messages (en_US, zh_TW, zh_CN, ja_JP, la_US)
language: en_US

# Autocomplete settings
autocomplete:
  # Maximum number of players to show in suggestions
  max-players: 100
